### ISSUE TITLE
[Feature ] node-kutt package

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/kutt-extension#17]
replacing axios call with node-kutt package

**Comment by aarjae** [comment]
I'd love to help with development for node, but what exactly are you trying to achieve?

**Comment by abhijithvijayan** [comment]
@aarjae I was thinking of using this package for the api call.
https://github.com/ardalanamini/node-kutt

I'm not sure about the quality response of that package.

**Comment by aarjae** [comment]
Oh okay, looks good. I will work on it :)

**Comment by aarjae** [comment]
Alright, I will work on it tonight

**Comment by abhijithvijayan** [comment]
#27
