### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/kutt-extension#31]
on right click

`shorten with kutt`

**Comment by abhijithvijayan** [comment]
Requires new permission 

https://developer.chrome.com/extensions/contextMenus

**Comment by aarjae** [comment]
Adding an option on browser right click to shorten url would be really cool. What's the current progress on it?
Still help wanted?

**Comment by abhijithvijayan** [comment]
@aarjae I was engaged with other projects.

You can give a PR if you managed to get it work. It needs context menu permission. Try it out.

**Comment by abhijithvijayan** [comment]
Simple click n shorten is enough I guess
