### ISSUE TITLE
Improve "copied" text UI

### ISSUE THREAD

**Issue by poeti8** [abhijithvijayan/kutt-extension#35]
Change the text to "Copied to clipboard.", make the color the same green as in Kutt and move it to the top of the URL (absolute position). Also, a little bit smaller maybe.
Just to make it look more like Kutt's website and also to get rid of the glitchy feeling caused by the change in the height.

**Comment by abhijithvijayan** [comment]
@poeti8 will do.

I managed to do that in the new history page.

**Comment by abhijithvijayan** [comment]
https://github.com/abhijithvijayan/kutt-extension/commit/5bd82e40f9c1d26317554fdbdff2a42d73804ba7

![](https://i.imgur.com/OuYX2EU.png)

@poeti8 Please test out the new release 1.0.0.
It includes these features
- Save History
- Auto Copy Kutt URL

Publish to stores if you find everything as expected and asked.

**Comment by poeti8** [comment]
Can you align with the URL, I mean, move it to the left.

**Comment by abhijithvijayan** [comment]
> Can you align with the URL, I mean, move it to the left.

![image](https://user-images.githubusercontent.com/34790378/52760473-a7e95f00-3035-11e9-879f-500b3dcbb828.png)
