### ISSUE TITLE
Regenerate Option

### ISSUE THREAD

**Issue by Relentlessy** [abhijithvijayan/kutt-extension#37]
1. When the link of long-website-name was created, show the link one and make a choice to "create new link" and "replace with new link (delete and generate the new one)"

(done) 2. Have an option, click the extension icon auto-generate and auto-copy link into clipboard

**Comment by abhijithvijayan** [comment]
@Relentlessy 

![2019-02-17_09-29-16](https://user-images.githubusercontent.com/34790378/52908191-a5397480-3296-11e9-8606-fae7ae0aba32.png)

Something like this might do. But doesn't the UI looks a bit cluttered?

**Comment by Relentlessy** [comment]
It's look good!

**Comment by poeti8** [comment]
No it doesn't look good. Why want a button to regenerate? If you click on the extension's icon it's going to create another link anyway.
@abhijithvijayan If you want to add this feature a button just like the copy button but with a "refresh" icon would look better in my opinion. Maybe put it between current icons.

**Comment by poeti8** [comment]
No it doesn't look good. Why want a button to regenerate? If you click on the extension's icon it's going to create another link anyway.
@abhijithvijayan If you want to add this feature a button just like the copy button but with a "refresh" icon would look better in my opinion. Maybe put it between current icons.

**Comment by abhijithvijayan** [comment]
> No it doesn't look good. Why want a button to regenerate? If you click on the extension's icon it's going to create another link anyway.
> @abhijithvijayan If you want to add this feature a button just like the copy button but with a "refresh" icon would look better in my opinion. Maybe put it between current icons.

I don't see any use of this feature at all.

**Comment by Relentlessy** [comment]
Ok

**Comment by abhijithvijayan** [comment]
> Ok

The features you mentioned are okay to work with but better left of with current ways. Anyway thanks for looking on to the extension. 👍

**Comment by Relentlessy** [comment]
@abhijithvijayan If I find the way to make the extension better I will share my opinion to you :)
