### ISSUE TITLE
Add custom link to extension

### ISSUE THREAD

**Issue by Relentlessy** [abhijithvijayan/kutt-extension#38]
User can change the generated link to their own if they user their own domain

**Comment by abhijithvijayan** [comment]
> User can change the generated link to their own if they user their own domain

You mean like custom kutt set up in their own servers and using api of that link?
or the domain feature within Kutt.it website?

**Comment by abhijithvijayan** [comment]
I set up a domain in Kutt.it website and saved the api key generated with that account in extension.

The urls automatically shorten to the domain added.

![2019-02-17_13-51-26](https://user-images.githubusercontent.com/34790378/52910271-34f11a00-32bb-11e9-8d06-0ef36461e383.png)

If the user wants a url like **http://domain.com/example** with **example** as the custom keyword, user has to use the website as adding that feature might complicate the simplicity of extension's purpose.

**Comment by Relentlessy** [comment]
Sorry for not clear. I mean when I generate the long link with my own domain and put on the custom word like https://pohui.net/mysteamprofile

But you're already explained it conflict with it extension ideal. Thank you :)

**Comment by abhijithvijayan** [comment]
> Sorry for not clear. I mean when I generate the long link with my own domain and put on the custom word like https://pohui.net/mysteamprofile
> 
> But you're already explained it conflict with it extension ideal. Thank you :)

It can be done but will not be idealistic.
