### ISSUE TITLE
[Feature] Work with Self Hosted Kutt

### ISSUE THREAD

**Issue by xianx** [abhijithvijayan/kutt-extension#43]
Hello,

Please add a config so the self host kutt (hosted on own cloud with own domain) can build extensions. config only need url of self hosted kutt.

**Comment by abhijithvijayan** [comment]
@poeti8 What do you think of this?

**Comment by abhijithvijayan** [comment]
@xianx I will work on it soon.

**Comment by abhijithvijayan** [comment]
@xianx This feature is now successfully implemented. Please test it out when v2.0.0 is updated to stores.

**Comment by abhijithvijayan** [comment]
Works from [Release 2.0.2](https://github.com/abhijithvijayan/kutt-extension/releases/tag/2.0.2)

**Comment by TheNoim** [comment]
Why is this not just a addon setting? Why so complicated?

**Comment by abhijithvijayan** [comment]
> Why is this not just a addon setting? Why so complicated?

Originally this extension was written for Kutt.it and was aimed to be that way. Since so many users deploy kutt and wanted the extension from the store itself, I thought it could be a developer feature to work with the self hosts.

**Comment by TheNoim** [comment]
Yeah, I obviously disagree with this. Why do I need to be a developer to use another host. Just make it a normal option. Maybe just label it as advanced.

**Comment by abhijithvijayan** [comment]
> Yeah, I obviously disagree with this. Why do I need to be a developer to use another host. Just make it a normal option. Maybe just label it as advanced.

Let me look on to that.

**Comment by TheNoim** [comment]
Thanks, yes.

**Comment by abhijithvijayan** [comment]
> Thanks, yes.

[v2.0.4](https://github.com/abhijithvijayan/kutt-extension/releases/tag/2.0.4) includes much more UI changes including this one.

**Comment by xianx** [comment]
@abhijithvijayan Though I am stated this topic but come after back a long time. Great improvements.

**Comment by abhijithvijayan** [comment]
This feature will warn users of new permission to access all sites.

**Comment by poeti8** [comment]
> This feature will warn users of new permission to access all sites.

Can we prevent this somehow?

**Comment by abhijithvijayan** [comment]
@poeti8 Only if we remove the feature in the next release. Also I don't see that much of difference in the weakly users count after the release. 

Most of the extensions come with access to all the sites. You could update the description in the stores about the new permission warning.
