### ISSUE TITLE
[BUG] Invalid Response!

### ISSUE THREAD

**Issue by uhlhosting** [abhijithvijayan/kutt-extension#50]
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/6324047/57798633-7c1d6880-774d-11e9-9750-c51c2b93329d.png">

I was just trying to test the beta extension on Nightly Firefox, and use Developer mode, test own instance at https://uhl.site . It fails as in screenshot.

**Comment by abhijithvijayan** [comment]
> <img alt="image" width="1159" src="https://user-images.githubusercontent.com/6324047/57798633-7c1d6880-774d-11e9-9750-c51c2b93329d.png">
> 
> I was just trying to test the beta extension on Nightly Firefox, and use Developer mode, test own instance at https://uhl.site . It fails as in screenshot.

This error response is when all the test case fails (status codes / valid response). Did you check your API status, see if it's working?

**Comment by abhijithvijayan** [comment]
@uhlhosting Your instance of kutt doesn't allow CORS.

![chrome_2019-05-16_04-14-49](https://user-images.githubusercontent.com/34790378/57814442-439f7e00-7791-11e9-9c60-0364cafca4de.png)

**Comment by abhijithvijayan** [comment]
> @uhlhosting Your instance of kutt doesn't allow CORS.
> 
> ![chrome_2019-05-16_04-14-49](https://user-images.githubusercontent.com/34790378/57814442-439f7e00-7791-11e9-9c60-0364cafca4de.png)

Also the manifest is set to request links to kutt.it only. I will work on changing it.

**Comment by abhijithvijayan** [comment]
@uhlhosting This should be fixed on release 2.0.1

**Comment by abhijithvijayan** [comment]
![chrome_2019-05-16_04-44-50](https://user-images.githubusercontent.com/34790378/57815895-f0c8c500-7796-11e9-8b97-6b62450dcb0c.png)

**Comment by uhlhosting** [comment]
@abhijithvijayan this works now great, I found that the function to automatically copy to clipboard, does not work, yet I do get a warning that it has been copied to clipboard on the extension.

Also would be great to have a feature to check if the current url was once shortened and to just reply with the original shortened url, to avoid entries on same address with several shortlinks, is no point in this.

**Comment by uhlhosting** [comment]
For example:
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/6324047/57828638-6e4b0000-77ac-11e9-8122-1175ae30f340.png">
we can wee I made some tests and we have 3 sites different url shortened. Maybe just to seek if it was previously shortened and recover it, or cache it...

**Comment by abhijithvijayan** [comment]
@uhlhosting please post the copy bug as a new issue. I will look on to that.

**Comment by abhijithvijayan** [comment]
@uhlhosting about that, the feature could only be given as optional one as if the user intent to re-shorten it for some reason, it could affect user experience.

**Comment by uhlhosting** [comment]
Would be great to have the option to Customize also URL's .

**Comment by abhijithvijayan** [comment]
@uhlhosting if custom url is what you're referring to,

**Comment by abhijithvijayan** [comment]
[Fixed] See comment

 https://github.com/abhijithvijayan/kutt-extension/issues/50#issuecomment-492860301
