### ISSUE TITLE
[BUG] Avoid URL DUPLICATES

### ISSUE THREAD

**Issue by uhlhosting** [abhijithvijayan/kutt-extension#51]
For example:
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/6324047/57828638-6e4b0000-77ac-11e9-8122-1175ae30f340.png">
we can wee I made some tests and we have 3 sites different url shortened. Maybe just to seek if it was previously shortened and recover it, or cache it...

**Comment by abhijithvijayan** [comment]
The best way to solve this is to replace the short url of the previously shortened same long url with the latest short url. Let me look on to that.
