### ISSUE TITLE
[BUG] Auto copy issue

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/kutt-extension#52]
auto copy url doesn't work

**Comment by uhlhosting** [comment]
This works sometimes not always, I am also testing Chrome/Opera . Any plans to add Safari support in future?

**Comment by abhijithvijayan** [comment]
@uhlhosting Safari doesn't not support webextensions api yet. Apple is not part of the W3C group which attempts to make a cross browser standard. So maybe in the future, when safari does support it, extension will work on it flawlessly. Also the next version of Microsoft edge will based on Chromium and so it will support kutt-extension.

**Comment by abhijithvijayan** [comment]
> This works sometimes not always, I am also testing Chrome/Opera . Any plans to add Safari support in future?

The issue is only with Firefox as I tested it out.

**Comment by abhijithvijayan** [comment]
#53 Fixes this
