### ISSUE TITLE
[Check] Are the final releases available in their APP Stores?

### ISSUE THREAD

**Issue by uhlhosting** [abhijithvijayan/kutt-extension#55]
IE Is version 2.3.0 available on FF Chrome and Opera Stores? 

https://addons.mozilla.org/en-US/firefox/addon/kutt/versions/

**Comment by abhijithvijayan** [comment]
@uhlhosting, @poeti8 handles the store updates.

**Comment by poeti8** [comment]
Now, yes.

**Comment by abhijithvijayan** [comment]
> Now, yes.

In chrome store too? I still see 1.0.3

**Comment by poeti8** [comment]
> In chrome store too? I still see 1.0.3

Yes, Chrome takes more time now, because of the permission that we want to access, they require a manual review.
