### ISSUE TITLE
[Feature] Safari support?

### ISSUE THREAD

**Issue by uhlhosting** [abhijithvijayan/kutt-extension#56]
Since Safari is default OSX Browser, guess would be great to have kutt.it in it. I would be glad to help with debugging solving issues for such.

**Comment by abhijithvijayan** [comment]
@uhlhosting I guess the extension has to be rewritten from scratch for safari.

I am not familiar with development for Safari.
If you are, I can create a new branch for you and you can start working on it?

**Comment by uhlhosting** [comment]
@abhijithvijayan was thinking is similar to some of existing browsers. Not familiar with it either.

**Comment by abhijithvijayan** [comment]
closing
