### ISSUE TITLE
[Feature] Show host domain specific items in UI

### ISSUE THREAD

**Issue by uhlhosting** [abhijithvijayan/kutt-extension#59]
In case one uses self hosted version of Kutt, would be great to have the linked url from 
- Custom Host ([Advanced](https://uhl.site/)) -> API Key: [(Get one)](https://uhl.site/login) this for my example:

<img width="891" alt="image" src="https://user-images.githubusercontent.com/6324047/58358498-6ad80880-7e7f-11e9-9975-bfd69c84b1b1.png">

You can see there in the left corner the link sends me to kutt.it/login, instead of sending me to my custom URL.

**Comment by abhijithvijayan** [comment]
@uhlhosting This is better implemented if I decide to rewrite the extension in React framework. Otherwise it's better to leave it that way.

**Comment by abhijithvijayan** [comment]
Extension requires a **custom API key** from the **custom host** itself if user is trying to use that option.

**Comment by abhijithvijayan** [comment]
Available from v4.0.0-beta.1

https://github.com/abhijithvijayan/kutt-extension/releases/tag/4.0.0-beta.1
