### ISSUE TITLE
[Permission] Access to data for all websites

### ISSUE THREAD

**Issue by hmnd** [abhijithvijayan/kutt-extension#60]
Could you please explain why this change is necessary? I have stopped using this extension as a result of this change.
![Access to data for all websites](https://i.hmnd.io/yq71kyhe.png)

**Comment by abhijithvijayan** [comment]
> Could you please explain why this change is necessary? I have stopped using this extension as a result of this change.
> ![Access to data for all websites](https://camo.githubusercontent.com/ff32afbeb107e4a1ff99d162492917676c3afd5e/68747470733a2f2f692e686d6e642e696f2f797137316b7968652e706e67)

The latest update enables this extension to use with hosts other than Kutt.it. In order for that to work, the extension has to access all `http://*/` and `https://*/` hosts to request shortening. 

It was set to `https://kutt.it/*` in the earlier versions.

See [this](https://github.com/abhijithvijayan/kutt-extension/commit/644ff25af1363f20c130b74641e61c1ce39f67fc) commit and [this](https://github.com/abhijithvijayan/kutt-extension/issues/43) issue to clarify.

Also, just to be clear, no personal data is collected with this extension. As for the permission, the extension has to have the ability to request to any host, the user sets.

eg: https://uhl.site

**Comment by YouTwitFace** [comment]
@abhijithvijayan I like the idea but I don't think that requesting this permission is a good idea.

**Comment by abhijithvijayan** [comment]
@YouTwitFace Literally almost all url shorteners out there, request this permission.

Inspect the manifest json of [this](https://robwu.nl/crxviewer/?crx=https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Fone-click-url-shortener%2Ffjnodoodcohggdkacpmiidjikhlihcdk)

**Comment by YouTwitFace** [comment]
@abhijithvijayan that still doesn't change my mind.

**Comment by abhijithvijayan** [comment]
@YouTwitFace The whole idea of Kutt is an open source url shortener for all. I just made the extension to work with the custom host. I even found that some hosts can give **response in under a second**.

Take uhl.site for instance. Sign up and test it out yourself to see if it was worth it.

**Comment by YouTwitFace** [comment]
@abhijithvijayan 
![change my mind](https://user-images.githubusercontent.com/32808683/58522515-ba277d00-818e-11e9-8ffa-59f7fe72edeb.png)

**Comment by abhijithvijayan** [comment]
Closing.
