### ISSUE TITLE
[BUG] Fix the custom url trail causing error

### ISSUE THREAD

**Issue by uhlhosting** [abhijithvijayan/kutt-extension#66]
When a user uses local kutt server and goes in address with a / it will fail to work, maybe a fix for this is not hard, a website would normally resolve both / and non trailing addresses.

**Comment by abhijithvijayan** [comment]
@uhlhosting please provide a test case.

**Comment by abhijithvijayan** [comment]
@uhlhosting Please test out the new release and if that doesn't resolve the issue, feel free to reopen the issue again
