### ISSUE TITLE
Release 

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/kutt-extension#70]
3.1.1 is released.

@poeti8

Store is behind 4 versions

**Comment by poeti8** [comment]
Oops, ok will do soon.

**Comment by poeti8** [comment]
@abhijithvijayan Get this warning from Chrome store:

<img width="596" alt="image" src="https://user-images.githubusercontent.com/23660003/70152912-47f69e80-16c3-11ea-9378-3d7d838afd84.png">

**Comment by abhijithvijayan** [comment]
So, sorry about that.

I am not sure what happened there.

Please delay the upgrade until I figure out what caused this error.

**Comment by abhijithvijayan** [comment]
Its a new warning as well as a suggestion raised ny chrome store.


I didn't change any permission since the last release

They are suggesting to use activeTab permission instead of Tabs permission.

I will accept the recommendation and switch to using it and test the new permission and will release it soon.


Will notify you once completed.

**Comment by poeti8** [comment]
Yes got the warning for previous versions too but didn't see activeTab suggestion, I thought it would be useful.

**Comment by abhijithvijayan** [comment]
@poeti8 I have changed `tabs` permission to `activeTab` and also refactored some code.

Even still, google might warn about broad host permissions as using `https://*/*` and `http://*/*` is required for the extension to request data to custom host api endpoint.

Ignore the warning if it shows up.

Please do update both the stores with version **3.2.1**

Thanks

**Comment by poeti8** [comment]
Submitted, thanks. And yes, still got the warning, it's not important at this point, the review just might take longer.
