### ISSUE TITLE
Feature: custom url shortening

### ISSUE THREAD

**Issue by kmanojkumar** [abhijithvijayan/kutt-extension#76]
I see that there is no option to set any custom URL, only the generated one has to be used? This doesn't solve the complete purpose. 

A great extension, though! Thanks @abhijithvijayan! 

I would highly appreciate it if you can come up with this solution.

**Comment by abhijithvijayan** [comment]
Actually, the extension is under huge refactoring.

This feature is also in the roadmap.

**Comment by abhijithvijayan** [comment]
For the progress, see https://github.com/abhijithvijayan/kutt-extension/tree/refactor/react-typescript

**Comment by abhijithvijayan** [comment]
https://camo.githubusercontent.com/38b402a28ef4833a4e91e07012620b4c56cb7513/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f72656c656173652f616268696a69746876696a6179616e2f6b7574742d657874656e73696f6e2e7376673f636f6c6f72423d626c7565

**Comment by abhijithvijayan** [comment]
Available from v4.0.0-beta.1

**Comment by abhijithvijayan** [comment]
https://github.com/abhijithvijayan/kutt-extension/releases/tag/4.0.0-beta.1
