### ISSUE TITLE
migrate to v2 api for link shortening

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/kutt-extension#77]
- [x] issue a warning message to users(who have set up custom target) about upgrading `kutt` shortener to [`v2 API`](https://github.com/thedevs-network/kutt)

If you have the warning message appear like this
![Screenshot from 2020-02-05 06-55-57](https://user-images.githubusercontent.com/34790378/73802847-e2b74a80-47e4-11ea-9139-361b5f21c640.png)

Please migrate to kutt.it v2 [latest release](https://github.com/thedevs-network/kutt)

If you have upgraded your custom hosted kutt to the latest version and still have this warning message, please ignore as the next release will remove the message(minor patch will be up just as the users are aware of v2 api)

Major update will take time as extension is rewritten from scratch

If you have any questions, please comment below.

**Comment by abhijithvijayan** [comment]
The refactored extension will by default use kutt v2 api.

**Comment by abhijithvijayan** [comment]
@poeti8 

Could you clarify these for the extension to work?
- Route for validating api key(with user details returned)
- do I need to prefer v2 links api over v1 shorten api route?
- Correct Route & Response body format of `settings` route you talked about

**Comment by poeti8** [comment]
@abhijithvijayan Here's the new API:
https://app.swaggerhub.com/apis/poeti8/Kutt/2.0.0

Let me know if need something,

**Comment by poeti8** [comment]
> Route for validating api key(with user details returned)

Use `/users` and see if response is 200 or 401.

> do I need to prefer v2 links api over v1 shorten api route?

Yes, from now on only use v2

> Correct Route & Response body format of settings route you talked about

You can see `/users`, let me know if something is missing.

**Comment by abhijithvijayan** [comment]
Migrating v1 api to v2 in the extension will introduce breaking changes for the users who have set up the extension to use with custom kutt.

I will release a version that will warn all custom-host users to upgrade their version of kutt to v2 as soon as possible.

The extension from v4.x.x(react version) will use kutt v2 by default.

I will notify you about the patched release of v3.x.x version

**Comment by abhijithvijayan** [comment]
@poeti8 The patched release v3.2.2 is now ready to be published to stores.

It will warn the self hosted kutt users about v2 API

![Screenshot from 2020-02-05 06-55-57](https://user-images.githubusercontent.com/34790378/73802781-b0a5e880-47e4-11ea-9989-14ac92c5222b.png)

**Comment by abhijithvijayan** [comment]
> @abhijithvijayan Here's the new API:
> [app.swaggerhub.com/apis/poeti8/Kutt/2.0.0](https://app.swaggerhub.com/apis/poeti8/Kutt/2.0.0)
> 
> Let me know if need something,

![Screenshot from 2020-02-05 14-08-23](https://user-images.githubusercontent.com/34790378/73825000-321b6c00-4821-11ea-8afb-64ba2bb0eb14.png)

**Comment by poeti8** [comment]
I think it's case sensitive, would you try `X-API-KEY`?

**Comment by abhijithvijayan** [comment]
@poeti8 still it doesnt work!!

**Comment by poeti8** [comment]
Pushed a fix, try again now.

**Comment by poeti8** [comment]
Any news on when it's going to be available? People are emailing me about this.

**Comment by abhijithvijayan** [comment]
I am working on it in the spare time.

I am trying to not break things(like existing features and keys stored in users browser storage to the latest scheme)

It would be a great help if you could work on the design(only the UI part)

Maybe just after I complete the basic features(it will be completed soon)

**Comment by abhijithvijayan** [comment]
Seamless migration is what I am hoping for.

Some additional one time scripts are also to be added(to be removed once the new version reaches all users)

**Comment by poeti8** [comment]
I wouldn't care about old links in the table, we can delete them. Not even sure if need a history table, even if needed so, can call the API to get latest links.

**Comment by abhijithvijayan** [comment]
That sounds better.

I haven't started on anything other than popup & options page

**Comment by abhijithvijayan** [comment]
@poeti8 The popup menu functionalities are almost complete(with styling & few more things to take care of)

Could you share UI for the screen to show after shortening(with short url / copy button / qr code button / maybe a back button as well) ?

**Comment by abhijithvijayan** [comment]
@poeti8 The [release 3.2.2](https://github.com/abhijithvijayan/kutt-extension/releases/tag/3.2.2) is not yet available in stores. Is there something wrong?

The new redesigned version will be soon up for testing & releasing which will use v2 API by default.

**Comment by poeti8** [comment]
Seems like the version is still 3.2.1, please bump up and I'll submit.

**Comment by abhijithvijayan** [comment]
> Seems like the version is still 3.2.1, please bump up and I'll submit.

Download it from https://github.com/abhijithvijayan/kutt-extension/releases/tag/3.2.2

The travis build override the build in `extension` branch with build from the new typescript release

So use the one from the link above for publishing

**Comment by abhijithvijayan** [comment]
Extension from V4.0.0-beta.1 uses v2 api

https://github.com/abhijithvijayan/kutt-extension/releases/tag/4.0.0-beta.1

**Comment by abhijithvijayan** [comment]
Check for a 404 error on url shortening, show custom error
